CREATE TABLE IF NOT EXISTS devices (
 id TEXT PRIMARY KEY, token_hash TEXT NOT NULL, subscription TEXT NOT NULL, expires INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS reminders (
 id TEXT PRIMARY KEY, device TEXT NOT NULL, at INTEGER NOT NULL, kind TEXT NOT NULL,
 attempts INTEGER NOT NULL DEFAULT 0, lease INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS reminders_due ON reminders(at, lease);
