import worker from './worker-bundle.js';
import assert from 'node:assert/strict';
import {createECDH, hkdfSync, createDecipheriv, randomBytes} from 'node:crypto';
const origin='https://tabinote-notify-test.hourensou2048.workers.dev';
const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
const jwk=await crypto.subtle.exportKey('jwk',pair.privateKey);
const publicKey=Buffer.concat([Buffer.from([4]),Buffer.from(jwk.x,'base64url'),Buffer.from(jwk.y,'base64url')]).toString('base64url');
const env={VAPID_PRIVATE_JWK:JSON.stringify(jwk),VAPID_PUBLIC_KEY:publicKey};
const req=(path,body,requestOrigin=origin)=>new Request(origin+path,{method:body?'POST':'GET',headers:{Origin:requestOrigin,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
assert.equal((await worker.fetch(req('/'),env)).status,200);
assert.match(await (await worker.fetch(req('/sw.js'),env)).text(),/notificationclick/);
assert.equal((await worker.fetch(req('/config'),{})).status,503);
assert.equal((await worker.fetch(req('/test',{subscription:{endpoint:'https://example.com'}}),env)).status,400);
assert.equal((await worker.fetch(req('/test',{},'https://evil.example'),env)).status,403);
let sent=0;
const ua=createECDH('prime256v1');ua.generateKeys();const auth=randomBytes(16);
globalThis.fetch=async(url,opts)=>{sent++;assert.equal(url,'https://web.push.apple.com/demo');assert.equal(opts.redirect,'manual');assert.equal(opts.headers['Content-Encoding'],'aes128gcm');const token=opts.headers.Authorization.match(/t=([^,]+)/)[1];const [a,b,c]=token.split('.');assert.equal(JSON.parse(Buffer.from(b,'base64url')).aud,'https://web.push.apple.com');assert.ok(await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},pair.publicKey,Buffer.from(c,'base64url'),new TextEncoder().encode(a+'.'+b)));
  // 別のNode暗号APIで端末側の復号を検証する。
  const body=Buffer.from(opts.body),salt=body.subarray(0,16),pub=body.subarray(21,21+body[20]);assert.equal(body.readUInt32BE(16),4096);
  const shared=ua.computeSecret(pub),info=Buffer.concat([Buffer.from('WebPush: info\0'),ua.getPublicKey(),pub]);
  const ikm=Buffer.from(hkdfSync('sha256',shared,auth,info,32));
  const cek=Buffer.from(hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: aes128gcm\0'),16));
  const nonce=Buffer.from(hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: nonce\0'),12));
  const encrypted=body.subarray(21+pub.length),dec=createDecipheriv('aes-128-gcm',cek,nonce);dec.setAuthTag(encrypted.subarray(-16));
  const clear=Buffer.concat([dec.update(encrypted.subarray(0,-16)),dec.final()]);assert.equal(clear.at(-1),2);assert.equal(JSON.parse(clear.subarray(0,-1)).body,'テスト通知が届きました。');
  return new Response(null,{status:201});};
const result=await worker.fetch(req('/test',{subscription:{endpoint:'https://web.push.apple.com/demo',keys:{p256dh:ua.getPublicKey().toString('base64url'),auth:auth.toString('base64url')}}}),env);
assert.equal(result.status,200);assert.equal((await result.json()).accepted,true);assert.equal(sent,1);
assert.equal((await worker.fetch(req('/test',{subscription:{endpoint:'https://web.push.apple.com/demo',keys:{p256dh:ua.getPublicKey().toString('base64url'),auth:auth.toString('base64url')}}}),env)).status,429);
globalThis.fetch=async()=>new Response(JSON.stringify({reason:'BadJwtToken'}),{status:403});
const rejected=await worker.fetch(req('/test',{subscription:{endpoint:'https://web.push.apple.com/demo2',keys:{p256dh:ua.getPublicKey().toString('base64url'),auth:auth.toString('base64url')}}}),env);
assert.equal((await rejected.json()).reason,'BadJwtToken');
console.log('PASS: routes, validation, VAPID signature, independent payload decryption, cooldown, provider error');
